### ISSUE TITLE
Tizen build on rnv@0.37.2 seems broken

### ISSUE THREAD

**Issue by bruno-sartori** [flexn-io/renative#1062]
After running `rnv build -p tizen -s release` i cant see any JS files on `platformBuilds/blank_tizen` folder and both index.html files have an `<%= injectedScripts %>` tag which means rnv failed to inject <script> tags.

1. After creating a new project with rnv@0.36.1 with tizen support type `rnv build -p tizen -s release`
2. See js files missing in `platformBuilds/blank_tizen` folder and index.html files without <script> tags

Expected behavior:
After building the project JS files should be properly included on final output

Screenshots:
![rnv_evidence](https://github.com/flexn-io/renative/assets/57626988/3c99910f-fe90-40d6-961b-6bd55a92a121)
![rnv_evidence_2](https://github.com/flexn-io/renative/assets/57626988/b2bd8000-f33c-4620-a75f-553b1d5522f4)
![image](https://github.com/flexn-io/renative/assets/57626988/7288cc3f-048c-4da4-a8a9-fe96b3510e2d)

Desktop:
-   OS: Windows 10
-   Node Version: 18.16.1
-   RNV Version: 0.36.1

**Comment by GabrieleKaceviciute** [comment]
@bruno-sartori thank you for reporting, this will be checked

**Comment by bruno-sartori** [comment]
@GabrieleKaceviciute Just to update you, I tested on rnv@0.37.2 and the bug still occurs.

**Comment by trokohl** [comment]
Is there a way to manually create only the build with bundle?
I need to build a new release and I can't get any other version than 0.37.3 to run. But with this I can not build a release?

**Comment by trokohl** [comment]
I don't know exactly how the build process in the directory was intended but here is my workaround.

**Step 1**
`rnv run -p tizen -s release`
=> build in platformBuilds/medienportal_tizen/build/

**Step 2**
`copy platformBuilds/myapp_tizen/*.* platformBuilds/myapp_tizen/build/`
=> config.xml and icon.png  are in the root and not in the build folder

**Step 3**
`C:/tizen-studio/tools/ide/bin/tizen.bat build-web -- ./platformBuilds/myapp_tizen/build -out ../buildTizen`
=> result is in ./platformBuilds/myapp_tizen/buildTizen

rnv do the following:
`C:\tizen-studio\tools\ide\bin\tizen.bat build-web -- <abspath>platformBuilds\myapp_tizen -out <abspath>platformBuilds\myapp_tizen\build`
what is wrong with the directory structure because the js-build is in den build folder and in <abspath>platformBuilds\myapp_tizen is only the config.xml, icon.png and a public folder with the debug index.html

**Step 4**
`C:/tizen-studio/tools/ide/bin/tizen.bat package -- ./platformBuilds/myapp_tizen/buildTizen -s mycertname -t wgt -o ./platformBuilds/myapp_tizen/output`
=> create the wgt file (perhabs you have to rename it if it contains blanks)

**Step 5**
`C:/tizen-studio/tools/ide/bin/tizen.bat install -n ./platformBuilds/myapp_tizen/output/myapp.wgt`
=> Install
