### ISSUE TITLE
Stable version for React Native 0.70+ 

### ISSUE THREAD

**Issue by ParvinderjitSF** [flexn-io/renative#1527]
What is the stable version of Re-Native for React Native 0.70+

**Comment by Parvinderjit** [comment]
Actually there is one of our client using this framework for his production app. Now we are facing some issue with this ReNative framework like some of the third party SDK not working properly with the old versions of the SDK from Android , iOS and React-Native version. 
And also there is another problem like need to add watchOS companion app to the ReNative project. It is humble request can you suggest how can we integrate watchOS App target into the ReNative project. Or any other way explicitly to increase the version of the ReactNative

One another question is why platformBuild folder created everytime? How can we add additional project target into the XCode project. I tried but next time when hitting the npx rnv run -p ios it replaces the old configuration. Can you sugget us how to achive this? 

It is bit urgent for us. Thanking you in advance

**Comment by RicardasN** [comment]
What version or ReNative are you using?

You can explicitly change React Native version via `renative.json` `plugins` by providing some sort of explicit version, that you need, however I'd expect some problems due to changes in React Native itself. It will be properly implemented in a newer release of ReNative itself - 1.0

To confirm you already have the WatchOS app done and want to connect it as a target in XCode? Or do you want transpilation of JS code, like for iOS/tvOS?

**Comment by Parvinderjit** [comment]
@RicardasN I am using Renative 0.34. I tried to increase the react native version to 0.68 because of some library dependency reasons. But Renative gets break. Even for the latest version it is not compilable and won't take any risk for the releasing of the app. 

And for the WatchOS app, we will create native app for the same. and planning to bridge it with ReNative app

**Comment by pauliusguzas** [comment]
1.0.0 was released with latest react-native, closing this tikcet
