### ISSUE TITLE
I can't run the project on Wabos

### ISSUE THREAD

**Issue by soliev-hasan** [flexn-io/renative#1744]
error: ⨯ ○ platform configure: Error: No Webos SDK found. Check if it is installed.
    at /Users/dilovar/Desktop/new/myApp/node_modules/@rnv/sdk-webos/src/installer.ts:44:15
    at step (/Users/dilovar/Desktop/new/myApp/node_modules/tslib/tslib.js:195:27)
    at Object.next (/Users/dilovar/Desktop/new/myApp/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/Users/dilovar/Desktop/new/myApp/node_modules/tslib/tslib.js:166:62)

**Comment by GabrieleKaceviciute** [comment]
@soliev-hasan Thanks for reporting this issue, could you provide rnv and node versions, webos simulator version, os type?

**Comment by soliev-hasan** [comment]
"@rnv/template-starter": "1.1.0",
node versions : v20.18.0,
 webos simulator version : 1.4.1
 os type : macOS

**Comment by pauliusguzas** [comment]
@soliev-hasan Are you sure you have webos sdk installed? if yes, then you need to add path to that sdk in `~/.rnv/renative.json`

**Comment by soliev-hasan** [comment]
ares --version
Version: 3.1.2

and yes there is no renative.json there

<img width="250" alt="Снимок экрана 2024-10-07 в 15 28 22" src="https://github.com/user-attachments/assets/2a6f87ab-14ba-4b70-ab2f-111359ef33ad">\

**Comment by soliev-hasan** [comment]
if you mean renative.json at the root of the project then here it is
<img width="491" alt="image" src="https://github.com/user-attachments/assets/0a3f2b5d-c46f-4611-8c1b-3ca333fc2871">

**Comment by Marius456** [comment]
Hello @soliev-hasan ,
I think there was a similar problem:
- https://github.com/flexn-io/renative/issues/1657
In following days there should be 1.3.0 live release or you can check 1.3.0-rc.2 where this problem is fixed.
Another solution is to add sdk path. You can find it in linked problem.

**Comment by soliev-hasan** [comment]
thanks, it worked, but now it displays an error on the webos sdk itself, don’t you know how to fix it?
<img width="899" alt="Снимок экрана 2024-10-08 в 09 56 53" src="https://github.com/user-attachments/assets/ef7f704c-8a53-43f9-9a82-5cbe9e9383e8">

**Comment by aurimasmi** [comment]
Do you have device setuped with `ares-setup-device`?

**Comment by soliev-hasan** [comment]
yes I even installed several devices via ares-setup-device

**Comment by Marius456** [comment]
Hello @soliev-hasan,
I little confused about your installed `ares`. You said that you have ares v3.1.2. 
However, from this error I see that you use old version of `ares` that you have in Desktop folder. I guessing it is old because it tries to run `ares-device-info` that is deprecated.

Here is screenshot when I try to run it with `ares v3.0.6`:
<img width="864" alt="image" src="https://github.com/user-attachments/assets/6d59abea-bb7b-469c-8808-cc21ba5f19a0">

Steps for you to try:
1.  Try to run `ares-device -D`
2.  If you get list of devices like in my screenshot, than try to temporary rename `CLI` folder in  `Desktop/new/webOS_TV_SDK` and run renative again.
3. If step 1 fails, try reinstalling webos/cli https://www.npmjs.com/package/@webos-tools/cli

Let me know if you need more help.

**Comment by soliev-hasan** [comment]
<img width="514" alt="image" src="https://github.com/user-attachments/assets/9fd90772-ee83-4673-bcfd-57fc02d0ada5">
<img width="710" alt="image" src="https://github.com/user-attachments/assets/56cff38c-2c77-4c13-b629-a1f47d80bf60">

**Comment by soliev-hasan** [comment]
hi Marius!
I tried absolutely everything, it still gives me the error luna Send, can you somehow install it on my device, for example through anydesk

**Comment by Marius456** [comment]
Hello @soliev-hasan,
Sorry, but I didn't encounter this error, so I can't help you with that. I see there is a problem with the connection of your webOS device. Try raising that issue in the webOS developer forum or on their GitHub page.
