### ISSUE TITLE
Version code on android defaults to 0

### ISSUE THREAD

**Issue by mihaiblaga89** [flexn-io/renative#974]
**Describe the bug**
If not specified RNV will default to 0
```
[ warn ] [configure] You are missing version prop in your config. will default to 0
```

However, android now fails with 
```
* What went wrong:
A problem occurred configuring project ':app'.
> com.android.builder.errors.EvalIssueException: android.defaultConfig.versionCode is set to 0, but it should be a positive integer.
  See https://developer.android.com/studio/publish/versioning#appversioning for more information.
```

**Comment by maciejsiiminski** [comment]
Check the versionCode prop inside your appConfigs/renative.json. If it is non-existent or set to zero change it to a positive number.

**Comment by pauliusguzas** [comment]
@mihaiblaga89 is there a way to test this?

**Comment by pauliusguzas** [comment]
@ElenaDiachenko cc

**Comment by ElenaDiachenko** [comment]
@GabrieleKaceviciute Check platformBuilds/<platform>/app/build.gradle.
Version code by default based on the renative version (  ReNative Version: 1.0.0-rc.4   => versionCode =  1000004). You can change this value in renative.json (platforms.android.versionCode). But keep in mind if this value is less than  value of the previous installed app, you'll get an error. This is expected behaviour .

**Comment by GabrieleKaceviciute** [comment]
@ElenaDiachenko
I get an error, the only way - if I set the "versionCode" value lower than zero, in all other cases - there is no error. Is it how it should be or is it bug?

**Comment by ElenaDiachenko** [comment]
VersionCode only accepts positive integers. Error, fixed here https://github.com/flexn-io/renative/pull/1323
